std = "roblox+astrakyn"

[lints]
almost_swapped = "deny"
deprecated = "deny"
divide_by_zero = "deny"
duplicate_keys = "deny"
empty_if = "deny"
global_usage = "deny"
if_same_then_else = "deny"
ifs_same_cond = "deny"
incorrect_standard_library_use = "deny"
mismatched_arg_count = "deny"
multiple_statements = "deny"
must_use = "deny"
parenthese_conditions = "deny"
shadowing = "deny"
suspicious_reverse_loop = "deny"
type_check_inside_call = "deny"
unbalanced_assignments = "deny"
undefined_variable = "deny"
unscoped_variables = "deny"
unused_variable = "deny"
